# Generated by Django 3.0.8 on 2020-07-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_titile',
            new_name='entry_title',
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
