# Generated by Django 3.0.8 on 2020-08-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20200729_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_image',
        ),
    ]
